config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "home#index"
  post 'post/:post_id/comments', to: 'comments#create', as: 'post_comment'
  get 'posts/ditum/:id', to: 'posts#ditumner', as: 'post_views'
  resources :posts
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/ditum.rb
class Ditum < ApplicationRecord
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
	has_many :comments
	has_one :ditum
	validates :title, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable      
  has_many :comments       
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

	add_flash_types :danger, :info, :success, :warning
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	def create
		@post = Post.find(params[:post_id])
		user = current_user.id
		@comment = @post.comments.create(user_id: user, post_id: @post, content: comment_params[:content])
		@comment.save
		redirect_to post_path(@post)
	end

	private
	def comment_params
		params.require(:comment).permit(:content)
	end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	before_action :find_post, only: %i[ show edit update destroy ]

	def index
		@posts = Post.all
	end

	def new
		@post = Post.new
	end

	def create
		@post = Post.new(post_params)
		if @post.save
			flash[:success] = t('posts.create')
			redirect_to post_path(@post)
		else
			flash[:danger] = t('posts.error')
			redirect_to new_post_path
		end
	end

	def show

	end

	def edit

	end

	def update
		@post.update(post_params)
		redirect_to post_path(@post)
	end

	def destroy
		@post.destroy
		redirect_to posts_path
	end
	
	def find_post
		@post = Post.find_by_id(params[:id])
	end

	def ditumner
		@post = Post.find(params[:id])
		if @post.ditum.present?
		@view = @post.ditum.ditumner + 1
		@post.ditum.update(ditumner: @view)
		redirect_to post_path(@post)
		else
			@views = @post.create_ditum(ditumner: 1)
			@views.save
			redirect_to post_path(@post)
		end
	end

	private

	
	def post_params
		params.require(:post).permit(:title, :content)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/_form.html.erb
<%= form_for(Comment.new,url: post_comment_path(@post)) do |f| %>
	<%= f.text_area :content %>
	<%= f.submit %>
<% end %>

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>


<%= button_to 'Log_Out', destroy_user_session_path, method: :delete %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Mysite</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
    <%= render "shared/flash" %>
  </body>
</html>

app/views/posts/edit.html.erb
<br>
<br>
<br>
<br>

<%= form_for @post do |f| %>
	<%= f.text_field :title %>
	<%= f.text_field :content %>
	<%= f.submit %>
<% end %>	

app/views/posts/index.html.erb
<br>
<br>
<br>
<br>

<% @posts.each  do |post| %>
	<h1><%= link_to post.title, post_views_path(post) %></h1>
	<p><%= post.content %></p>
<% end %>	

app/views/posts/new.html.erb
<br>
<br>
<br>
<br>

<%= form_for @post do |f| %>
	<%= f.text_field :title %>
	<%= f.text_field :content %>
	<%= f.submit %>
<% end %>	

app/views/posts/show.html.erb
<% if @post.present? %>
<br>
<br>
<br>
<br>

<%= link_to 'New', new_post_path %>
<%= link_to 'Posts', posts_path %>
<h1><%= @post.title %></h1>
<p><%= @post.content %></p>
<%= link_to 'Edit', edit_post_path %>
<%= button_to 'Delete', @post, method: :delete %>
<br>

<% if current_user %>
	<%= render 'comments/form' %>
	<% else %>
	<textarea disabled></textarea>
<% end %>

<% @post.comments.each do |comment| %>
	<p>
		<%= comment.content %>
	</p>
	<p>
		<%= comment.user.email %>
	</p>
<% end %>

<% if @post.ditum.present? %>
	<p>
		<%= @post.ditum.ditumner %> views
	</p>
<% end %>
<% end %>

app/views/shared/_flash.html.erb
<div class="container">
	<% flash.each do |type,msg| %>
		<div class="alert alert-<%= type %> %>
			alert-dismissible fade show" role="alert">
			<%= msg %>
			<button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>	
		</div>
	<% end %>
</div>			